version: "3.6"
services:
  database:
    container_name: stator-postgres
    ports:
      - 5433:5432
    restart: always
    image: postgres:latest
    command:
      - postgres
      - -c
      - listen_addresses=*
    environment:
      POSTGRES_DB: stator
      POSTGRES_HOST_AUTH_METHOD: "trust" # Not recommended, only for demo purposes
    volumes:
      - ./database:/var/lib/postgresql
